import stringsoflanguages from '../localize';
var CommanString = {radadiya:
        {
            "Atulbhai labhubhai Radadiya" :stringsoflanguages.AtulbhailabhubhaiRadadiya,
            "Madhubhai Pragjibhai Radadiya":stringsoflanguages.MadhubhaiPragjibhaiRadadiya,
            "Akshit Dalsukhbhai Radadiya":	stringsoflanguages.AkshitDalsukhbhaiRadadiya,
            "Amit Ashvinbhai Radadiya":	stringsoflanguages.AmitAshvinbhaiRadadiya,
            "Ashvinbhai jivrajbhai Radadiya":	stringsoflanguages.AshvinbhaijivrajbhaiRadadiya,
            "Arvindbhai Popatbhai Radadiya":	stringsoflanguages.ArvindbhaiPopatbhaiRadadiya,
            "Arvindbhai Veerjibhai Radadiya":	stringsoflanguages.ArvindbhaiVeerjibhaiRadadiya,
            "Alpeshbhai Vinubbhai Radadiya":	stringsoflanguages.AlpeshbhaiVinubbhaiRadadiya,
            "Ashokbhai Devchandbhai Radadiya":	stringsoflanguages.AshokbhaiDevchandbhaiRadadiya,
            "Ashvinbhai Narayanbhai Radadiya":	stringsoflanguages.AshvinbhaiNarayanbhaiRadadiya,
            "Ashvinbhai labhubhai Radadiya":	stringsoflanguages.AshvinbhailalibhaiRadadiya,
            "Ashvinbhai Vitthalbhai Radadiya":	stringsoflanguages.AshvinbhaiVitthalbhaiRadadiya,
            "Ashtik Prakashbhai Radadiya":	stringsoflanguages.AshtikPrakashbhaiRadadiya,
            "Uttam Laljibhai Radadiya":	stringsoflanguages.UttamLaljibhaiRadadiya,
            "Uttambhai Ghanshyambhai Radadiya":	stringsoflanguages.UttambhaiGhanshyambhaiRadadiya,
            "Urvishbhai Lalitbhai Radadiya":	stringsoflanguages.UrvishbhaiLalitbhaiRadadiya,
            "Kanubhai Dhirubhai Radadiya":	stringsoflanguages.KanubhaiDhirubhaiRadadiya,
            "Kapilbhai pravinbhai Radadiya":stringsoflanguages.KapilbhaipravinbhaiRadadiya,
            "Kapilbhai himatbhai Radadiya":	stringsoflanguages.KapilbhaihimatbhaiRadadiya,
            "Kamleshbhai Arvindbhai Radadiya":	stringsoflanguages.KamleshbhaiArvindbhaiRadadiya,
            "Kashyapbhai Vinubhai Radadiya":stringsoflanguages.KashyapbhaiVinubhaiRadadiya,
            "Kantibhai Lavjibhai Radadiya":	stringsoflanguages.KantibhaiLavjibhaiRadadiya,
            "Kantibhai Gangdasbhai Radadiya":stringsoflanguages.KantibhaiGangdasbhaiRadadiya,
            "Kantibhai Bhavnabhai Radadiya":	stringsoflanguages.KantibhaiBhanabhaiRadadiya,
            "Kantibhai Vitthalbhai Radadiya":stringsoflanguages.KantibhaiVitthalbhaiRadadiya,
            "Kishorbhai Babubhai Radadiya":	stringsoflanguages.KishorbhaiBabubhaiRadadiya,
            "Ketanbhai Rameshbhai Radadiya":stringsoflanguages.KetanbhaiRameshbhaiRadadiya,
            "Kaushik Dineshbhai Radadiya":	stringsoflanguages.KaushikDineshbhaiRadadiya,
            "Gabharubhai Bhurabhai Radadiya":stringsoflanguages.GubharubhaiBhurabhaiRadadiya,
            "Girdharbhai Pragjibhai Radadiya":stringsoflanguages.GirdharbhaiPragjibhaiRadadiya,
            "Gordhanbhai Veerjibhai Radadiya":stringsoflanguages.GordhanbhaiVeerjibhaiRadadiya,
            "Gautam himatbhai Radadiya": stringsoflanguages.GautamhimatbhaiRadadiya,
            "ghanshyam narayanbhai Radadiya":	stringsoflanguages.ghanshyamnarayanbhaiRadadiya,
            "Ghanshyam Balubhai Radadiya":	stringsoflanguages.GhanshyamBalubhaiRadadiya,
            "Ghanshyamikumar Mansukhbhai Radadiya":	stringsoflanguages.GhanshyamikumarMansukhbhaiRadadiya,
            "Ghanshyambhai Balubhai Radadiya":	stringsoflanguages.GhanshyambhaiBalubhaiRadadiya,
            "Ghanshyambhai Vinubhai Radadiya":	stringsoflanguages.GhanshyambhaiVinubhaiRadadiya,
            "Ghanshyambhai Shambubhai Radadiya":	stringsoflanguages.GhanshyambhaiShambubhaiRadadiya,
            "Chandubhai Dulabhai Radadiya":	stringsoflanguages.ChandubhaiDulabhaiRadadiya,
            "Chimanbhai Vinubhai Radadiya":	stringsoflanguages.ChimanbhaiVinubhaiRadadiya,
            "Chimanbhai Dhirubhai Radadiya":	stringsoflanguages.ChimanbhaiDhirubhaiRadadiya,
            "Chunilal ParshottamBhai Radadiya":stringsoflanguages.ChunilalParshottamBhaiRadadiya,
            "Jagdishbhai Kantibhai Radadiya":stringsoflanguages.JagdishbhaiKantibhaiRadadiya,
            "Jayraj Arvindbhai Radadiya":	stringsoflanguages.JayrajArvindbhaiRadadiya,
            "Jaysukhbhai Khimjibhai Radadiya":	stringsoflanguages.JaysukhbhaiKhimjibhaiRadadiya,
            "Jitubhai Kantibhai Radadiya":	stringsoflanguages.JitubhaiKantibhaiRadadiya,
            "Tarachandbhai Vitthalbhai Radadiya":stringsoflanguages.TarachandbhaiVitthalbhaiRadadiya,
            "Dalsukhbhai Ravjibhai Radadiya":stringsoflanguages.DalsukhbhaiRavjibhaiRadadiya,
            "Dineshbhai Parshtambhai Radadiya":stringsoflanguages.DineshbhaiParshtambhaiRadadiya,
            "Dulabhai Gopalbhai Radadiya":stringsoflanguages.DulabhaiGopalbhaiRadadiya,
            "Dhirubhai Gopabhai Radadiya":stringsoflanguages.DhirubhaiGopabhaiRadadiya,
            "Dhirubhai Muljibhai Radadiya":stringsoflanguages.DhirubhaiMuljibhaiRadadiya,
            "Narendrabhai Bavchandbhai Radadiya":stringsoflanguages.NarendrabhaiBavchandbhaiRadadiya,
            "Nathabhai Madhubhai Radadiya":stringsoflanguages.NathabhaiMadhubhaiRadadiya,
            "narayanbhai Ranchodbhai Radadiya":stringsoflanguages.narayanbhaiRanchodbhaiRadadiya,
            "Narayanbhai Devrajbhai Radadiya":stringsoflanguages.NarayanbhaiDevrajbhaiRadadiya,
            "Nikunjbhai Himatbhai Radadiya":stringsoflanguages.NikunjbhaiHimatbhaiRadadiya,
            "Nikunjbhai Dhirubhai Radadiya":stringsoflanguages.NikunjbhaiDhirubhaiRadadiya,
            "Nitinbhai Jaysukhbhai Radadiya":stringsoflanguages.NitinbhaiJaysukhbhaiRadadiya,
            "Nipulbhai Mansukhbhai Radadiya":stringsoflanguages.NipulbhaiMansukhbhaiRadadiya,
            "Nileshbhai Bavchandbhai Radadiya":stringsoflanguages.NileshbhaiBavchandbhaiRadadiya,
            "NitinKumar Jaysukhbhai Radadiya":stringsoflanguages.NitinKumarJaysukhbhaiRadadiya,
            "Pareshbhai pravinbhai Radadiya":stringsoflanguages.PareshbhaipravinbhaiRadadiya,
            "Prakashbhai Babubhai Radadiya":stringsoflanguages.PrakashbhaiBabubhaiRadadiya,
            "Pravinbhai Ravjibhai Radadiya":stringsoflanguages.PravinbhaiRavjibhaiRadadiya,
            "pravinbhai Gangdasbhai Radadiya":	stringsoflanguages.pravinbhaiGangdasbhaiRadadiya,
            "pravinbhai Ravjibhai Radadiya":	stringsoflanguages.pravinbhaiRavjibhaiRadadiya,
            "Babubhai Popatbhai Radadiya":stringsoflanguages.BabubhaiParatbhaiRadadiya,
            "Babubhai Balubhai Radadiya":stringsoflanguages.BabubhaiBalubhaiRadadiya,
            "Balubhai Gopalbhai Radadiya":	stringsoflanguages.BalubhaiGopalbhaiRadadiya,
            "Bhanubhai Bhavanbhai Radadiya":stringsoflanguages.BhanubhaiBhanabhaiRadadiya,
            "Bharatbhai Babubhai Radadiya":	stringsoflanguages.BharatbhaiBabubhaiRadadiya,
            "Bharatbhai Khimjibhai Radadiya":	stringsoflanguages.BharatbhaiKhimjibhaiRadadiya,
            "Bhaveshbhai Khimjibhai Radadiya":	stringsoflanguages.BhaveshbhaiKhimjibhaiRadadiya,
            "Manthan Arvindbhai Radadiya":	stringsoflanguages.ManthanArvindbhaiRadadiya,
            "Madhubhai Devrajbhai Radadiya":	stringsoflanguages.MadhubhaiDevrajbhaiRadadiya,
            "Manjibhai Premjibhai Radadiya":	stringsoflanguages.ManjibhaiPremjibhaiRadadiya,
            "Mansukhbhai Bhavanbhai Radadiya":	stringsoflanguages.MansukhbhaiBhavanbhaiRadadiya,
            "Mansukhbhai Ranchhodbhai Radadiya":stringsoflanguages.MansukhbhaiRanchhodbhaiRadadiya,
            "Mansukhbhai Virjibhai Radadiya":stringsoflanguages.MansukhbhaiVirjibhaiRadadiya,
            "Mansukhbhai Bachubhai Radadiya":	stringsoflanguages.MansukhbhaiBachubhaiRadadiya,
            "Mayankbhai Ghanshyambhai Radadiya":stringsoflanguages.MayankbhaiGhanshyambhaiRadadiya,
            "Mahir Nileshbhai Radadiya":	stringsoflanguages.MahirNileshbhaiRadadiya,
            "MaheshBhai narayanbhai Radadiya":stringsoflanguages.MaheshbhainarayanbhaiRadadiya,
            "Maheshbhai Bhanubhai Radadiya":	stringsoflanguages.MaheshbhaiBhanubhaiRadadiya,
            "Mukeshbhai Girdharbhai Radadiya": stringsoflanguages.MukeshbhaiGirdharbhaiRadadiya,
            "Mukeshbhai Gordhanbhai Radadiya":	stringsoflanguages.MukeshbhaiGordhanbhaiRadadiya,
            "Maulikbhai Sureshbhai Radadiya":stringsoflanguages.MaulikbhaiSureshbhaiRadadiya,
            "Yogeshbhai Gordhanbhai Radadiya":	stringsoflanguages.YogeshbhaiGordhanbhaiRadadiya,
            "Rajubhai Dulabhai Radadiya":	stringsoflanguages.RajubhaiDulabhaiRadadiya,
            "Rameshbhai Lavjibhai Radadiya":	stringsoflanguages.RameshbhaiLavjibhaiRadadiya,
            "Rameshbhai Parshtambhai Radadiya":stringsoflanguages.RameshbhaiParshtambhaiRadadiya,
            "Rasakbhai Devchandbhai Radadiya":	stringsoflanguages.RakshabhaiDevchandbhaiRadadiya,
            "Rajeshbhai Laljibhai Radadiya":	stringsoflanguages.RajeshbhaiLaljibhaiRadadiya,
            "Rajeshbhai Madhubhai Radadiya":	stringsoflanguages.RajeshbhaiMadhubhaiRadadiya,
            "Ramjibhai Girharbhai Radadiya":	stringsoflanguages.RamjibhaiGirharbhaiRadadiya,
            "Lalitbhai Manjibhai Radadiya":	stringsoflanguages.LalitbhaiManjibhaiRadadiya,
            "Lalitbhai Rameshbhai Radadiya":stringsoflanguages.LalitbhaiRameshbhaiRadadiya,
            "Vajubhai Manjibhai Radadiya":	stringsoflanguages.VajubhaiManjibhaiRadadiya,
            "Vajendrabhai Nathabhai Radadiya":stringsoflanguages.VajendrabhaiNathabhaiRadadiya,
            "Vasudevbhai Gabhrubhai Radadiya":stringsoflanguages.VasudevbhaiGabhrubhaiRadadiya,
            "Vijaybhai Vinubhai Radadiya":stringsoflanguages.VijaybhaiVinubhaiRadadiya,
            "Vitthalbhai Gopabhai Radadiya":stringsoflanguages.VitthalbhaiGopabhaiRadadiya,
            "Vinubhai Virjibhai Radadiya":	stringsoflanguages.VinubhaiVirjibhaiRadadiya,
            "Vinubhai Popatbhai Radadiya":	stringsoflanguages.VinubhaiPopatbhaiRadadiya,
            "Vinubhai Balubhai Radadiya":	stringsoflanguages.VinubhaiBalubhaiRadadiya,
            "Vinubhai bhurabhai Radadiya":	stringsoflanguages.VinubhaibhurabhaiRadadiya,
            "VimalBhai Bhanubhai Radadiya":	stringsoflanguages.VimalbhaiBhanubhaiRadadiya,
            "Vivek jivrajbhai Radadiya":stringsoflanguages.VivekjivrajbhaiRadadiya,
            "Vivekbhai Ashvinbhai Radadiya":stringsoflanguages.VivekbhaiAshvinbhaiRadadiya,
            "Vishal pravinbhai Radadiya":	stringsoflanguages.VishalpravinbhaiRadadiya,
            "Vishalkumar Ashokbhai Radadiya":stringsoflanguages.VishalkumarAshokbhaiRadadiya,
            "Sanjaybhai Madhubhai Radadiya":stringsoflanguages.SanjaybhaiMadhubhaiRadadiya,
            "Sanjaybhai Vinubhai Radadiya":	stringsoflanguages.SanjaybhaiVinubhaiRadadiya,
            "Satishbhai Vajibhai Radadiya":	stringsoflanguages.SatishbhaiVajibhaiRadadiya,
            "Sagar Tarachandbhai Radadiya":	stringsoflanguages.SagarTarachandbhaiRadadiya,
            "Sureshbhai Vitthalbhai Radadiya":	stringsoflanguages.SureshbhaiVitthalbhaiRadadiya,
            "Sureshbhai Shambubhai Radadiya":stringsoflanguages.SureshbhaiShambubhaiRadadiya,
            "HariKrishanbhai Jaysukhbhai Radadiya":	stringsoflanguages.HariKrishanbhaiJaysukhbhaiRadadiya,
            "HariKrishanbhai Devchandbhai Radadiya":	stringsoflanguages.HarikrishnaBhaiDevchandbhaiRadadiya,
            "Harikrishnabhai Mukeshbhai Radadiya":	stringsoflanguages.HarikrishnabhaiMukeshbhaiRadadiya,
            "Hareshkumar Jaysukhbhai Radadiya":stringsoflanguages.HareshkumarJaysukhbhaiRadadiya,
            "Hareshbhai himatbhai Radadiya":stringsoflanguages.HareshbhaihimatbhaiRadadiya,
            "Harshadbhai Mansukhbhai Radadiya":	stringsoflanguages.HarshadbhaiMansukhbhaiRadadiya,
            "Harshilbhai Lalitbhai Radadiya":stringsoflanguages.HarshilbhaiLalitbhaiRadadiya,
            "Hardik Ghanshyambhai Radadiya":stringsoflanguages.HardikGhanshyambhaiRadadiya,
            "Hardikbhai Mansukhbhai Radadiya":stringsoflanguages.HardikbhaiMansukhbhaiRadadiya,
            "Hardikbhai Mukeshbhai Radadiya":stringsoflanguages.HardikbhaiMukeshbhaiRadadiya,
            "Himatbhai Labhubhai Radadiya":	stringsoflanguages.HimatbhaiLabhubhaiRadadiya,
            "Himatbhai Gangdasbhai Radadiya":	stringsoflanguages.HimatbhaiGangdasbhaiRadadiya,
            "himatbhai jivrajbhai Radadiya":stringsoflanguages.himatbhaijivrajbhaiRadadiya,
            "Hiren Pravinbhai Radadiya":stringsoflanguages.HirenPravinbhaiRadadiya,
            "Devchandbhai Jethabhai Radadiya":stringsoflanguages.DevchandbhaiJethabhaiRadadiya,
            "Parshtambhai Keshavbhai Radadiya":stringsoflanguages.ParshtambhaiKeshavbhaiRadadiya,
            "Vinubhai Parshotambhai Radadiya":stringsoflanguages.VinubhaiParshottambhaiRadadiya,
            "Mukeshbhai Parshotambhai Radadiya":stringsoflanguages.MukeshbhaiParshitbhaiRadadiya,
            "Harjibhai Jivanbhai Radadiya":stringsoflanguages.HarijibhaiJeevanbhaiRadadiya,
            "Jaysukhbhai Jivanbhai Radadiya":stringsoflanguages.jaysukhbhaijivanbhaiRadadiya,
            "Bhupatbhai jivanbhai Radadiya":stringsoflanguages.BhupatbhaijivanbhaiRadadiya,
            "Vitthalbhai Muljibhai Radadiya":stringsoflanguages.VitthalbhaiMuljibhaiRadadiya,
            "Sanjaybhai Vitthalbhai Radadiya":stringsoflanguages.SanjaybhaiVitthalbhaiRadadiya,
            "Vijaybhai Vitthalbhai Radadiya":stringsoflanguages.VijaybhaiVitthalbhaiRadadiya,
            "Arvindbhai Muljibhai Radadiya":stringsoflanguages.ArvindbhaiMuljibhaiRadadiya,
            "Bhikhubhai Laljibhai Radadiya":stringsoflanguages.BhikhubhaiLaljibhaiRadadiya,
            "Manyak Ghanshyambhai Radadiya" : stringsoflanguages.ManyakGhanshyambhaiRadadiya,
            "Mehulbhai Gobarbhai Radadiya":stringsoflanguages.MehulbhaiGobarbhaiRadadiya,
            "Nikulbhai Dhirubhai Radadiya":stringsoflanguages.NikulbhaiDhirubhaiRadadiya,
            "Sudhirbhai Bharatbhai Radadiya":stringsoflanguages.SudhirbhaiBharatbhaiRadadiya,
            "Uttam kanubhairadadiya":stringsoflanguages.Uttamkanubhairadadiya,
            "Viral RamesbhaiRadadiya":stringsoflanguages.ViralRamesbhaiRadadiya,
            "Yogeshbhai HarjibhaiRadadiya":stringsoflanguages.YogeshbhaiHarjibhaiRadadiya,
            "Ketan babubhaiRadadiya":stringsoflanguages.KetanbabubhaiRadadiya,
            "Kanubhai RanchhodbhaiRadadiya":stringsoflanguages.KanubhaiRanchhodbhaiRadadiya,
            "Ishwar bhaiKantibhaiRadadiya":stringsoflanguages.IshwarbhaiKantibhaiRadadiya,
            "Hasu KantibhaiRadadiya":stringsoflanguages.HasuKantibhaiRadadiya,
            "Harjibhai DeungarshbhaiRadadiya":stringsoflanguages.HarjibhaiDeungarshbhaiRadadiya,
            "Bharatbhai DungarshbhaiRadadiya":stringsoflanguages.BharatbhaiDungarshbhaiRadadiya,
            "Gobarbhai Nagjibhai Radadiya":stringsoflanguages.GobarbhaiNagjibhaiRadadiya,
            "Dipakbhai gobarbhai Radadiya":stringsoflanguages.DipakbhaigobarbhaiRadadiya,
            "Manthan babubhai Radadiya":stringsoflanguages.ManthanbabubhaiRadadiya
        },
    dhakecha:{
        "krunalbhai Sureshbhai Dhankecha":stringsoflanguages.krunalbhaiSureshbhaiDhankecha,
        "Gobarbhai Narshibhai Dhankecha":stringsoflanguages.GobarbhaiNarshibhaiDhankecha,
        "Ghanshyambhai bhupatbhai Dhankecha":stringsoflanguages.GhanshyambhaibhupatbhaiDhankecha,
        "Parshotambhai Ravjibhai Dhankecha":stringsoflanguages.ParshotambhaiRavjibhaiDhankecha,
        "Piyushbhai Rameshbhai Dhankecha":	stringsoflanguages.PiyushbhaiRameshbhaiDhankecha,
        "Balubhai Parshotambhai Dhankecha":	stringsoflanguages.BalubhaiParshotambhaiDhankecha,
        "Bhargavbhai Devchandbhai Dhankecha":stringsoflanguages.BhargavbhaiDevchandbhaiDhankacha,
        "Bhupatbhai Popatbhai Dhankecha":stringsoflanguages.BhupatbhaiPopatbhaiDhankakecha,
        "Mansukhbhai Dayalbhai Dhankecha":stringsoflanguages.MansukhbhaiDayalbhaiDhankecha,
        "Manishbhai Devchandbhai Dhankecha":stringsoflanguages.ManishbhaiDevchandbhaiDhankecha,
        "Mayurbhai Gobarbhai Dhankecha":stringsoflanguages.MayurbhaiGobarbhaiDhankecha,
        "Mehulbhai Rameshbhai Dhankecha":stringsoflanguages.MehulbhaiRameshbhaiDhankacha,
        "Rameshbhai Ravjibhai Dhankecha":stringsoflanguages.RameshbhaiRavjibhaiDhankecha,
        "Rajeshbhai Bhupatbhai Dhankecha":stringsoflanguages.RajeshbhaiBhupatbhaiDhankecha,
        "Sanjaybhai Bhupatbhai Dhankecha":stringsoflanguages.SanjaybhaiBhupatbhaiDhankacha,
        "Sureshbhai Parshotambhai  Dhankecha":stringsoflanguages.SureshbhaiParshotambhaiDhankecha,
    },
    shingala:{
        "Jaysukhabhai labhubhai Shingala":	stringsoflanguages.JaysukhabhailabhubhaiShingala,
        "Ketanbhai Jaysukhabhai Shingala":	stringsoflanguages.KetanbhaiJaysukhabhaiShingala,
        "Gokulbhai Jaysukhabhai Shingala":	stringsoflanguages.GokulbhaiJaysukhabhaiShingala,
        "Ashokbhai labhubhai Shingala":	stringsoflanguages.AshokbhailabhubhaiShingala,
        "Bhavinbhai Ashokbhai Shingala":stringsoflanguages.BhavinbhaiAshokbhaiShingala,
        "Bhadreshbhai Ashokbhai Shingala":stringsoflanguages.BhadreshbhaiAshokbhaiShingala,
        "Nileshbhai labhubhai Shingala":stringsoflanguages.NileshbhailabhubhaiShingala,
        "Gautambhai Nileshbhai Shingala":stringsoflanguages.GautambhaiNileshbhaiShingala,
        "Maulikbhai Nileshbhai Shingala":stringsoflanguages.MaulikbhaiNileshbhaiShingala,
        "Ghanshyam labhubhai Shingala":stringsoflanguages.GhanshyamlabhubhaiShingala,
    },
    sojitra:{
        "Himmatbhai Ravjeebhai sojitra":stringsoflanguages.HimmatbhaiRavjeebhaiSojitra,
        "Chetanbhai Himmatbhai sojitra":stringsoflanguages.ChetanbhaiHimmatbhaiSojitra,
        "Ashishbhai Himmatbhai sojitra":stringsoflanguages.AshishbhaiHimmatbhaiSojitra,
        "Babubhai Ravjeebhai sojitra":stringsoflanguages.BabubhaiRavjeebhaiSojitra,
        "Rameshbhai Ravjibhai Sojatra":stringsoflanguages.RameshbhaiRavjibhaiSojatra,
    }};
export default CommanString;
