import React from 'react';
import LocalizedStrings from 'react-native-localization';

// CommonJS syntax
// let LocalizedStrings  = require ('react-native-localization');

let strings = new LocalizedStrings({
    "gu":{
        radadiya:"રાદડિયા",
        Dhankecha:"ઢાંકેચા",
        Shingala:"શિંગાળા",
        sojitra:"સોજીત્રા",
        namavali:"નામાવલી",
        mobileNo:"મોબાઇલ નં.",
        AtulbhailabhubhaiRadadiya : "અતુલભાઈ લાભુભાઈ રાદડિયા",
        AkshitDalsukhbhaiRadadiya:	"અક્ષીત દલસુખભાઈ રાદડિયા",
        AmitAshvinbhaiRadadiya:	"અમિત અશ્વિનભાઈ રાદડિયા",
        ArvindbhaiPopatbhaiRadadiya:"અરવિંદભાઈ પોપટભાઈ રાદડિયા",
        ArvindbhaiMuljibhaiRadadiya:"અરવિંદભાઈ મુળજીભાઈ રાદડિયા",
        ArvindbhaiVeerjibhaiRadadiya:"અરવિંદભાઈ વીરજીભાઈ રાદડિયા",
        AlpeshbhaiVinubbhaiRadadiya:"અલ્પેશભાઈ  વિનુભાઈ રાદડિયા",
        AshokbhaiDevchandbhaiRadadiya:"અશોકભાઈ દેવચંદભાઈ રાદડિયા",
        AshvinbhaijivrajbhaiRadadiya:"અશ્વિનભાઈ જીવરાજભાઈ રાદડિયા",
        AshvinbhaiNarayanbhaiRadadiya:"અશ્વિનભાઈ નારાયણભાઈ રાદડિયા",
        AshvinbhailalibhaiRadadiya:"અશ્વિનભાઈ લાભુભાઈ રાદડિયા",
        AshvinbhaiVitthalbhaiRadadiya:"અશ્વિનભાઈ વિઠ્ઠલભાઈ  રાદડિયા",
        AshtikPrakashbhaiRadadiya:"આશતિક પ્રકાશભાઈ રાદડિયા",
        UttamLaljibhaiRadadiya:"ઉત્તમ લાલજીભાઈ રાદડિયા",
        UttambhaiGhanshyambhaiRadadiya:"ઉત્તમભાઈ ઘનશ્યામભાઈ રાદડિયા",
        UrvishbhaiLalitbhaiRadadiya:"ઉર્વીશભાઈ લલિતભાઈ રાદડિયા",
        KanubhaiDhirubhaiRadadiya:"કનુભાઈ ધીરુભાઈ રાદડિયા",
        KapilbhaipravinbhaiRadadiya:"કપિલભાઈ  પ્રવીણભાઈ રાદડિયા",
        KapilbhaihimatbhaiRadadiya:"કપિલભાઈ હિંમતભાઇ રાદડિયા",
        KamleshbhaiArvindbhaiRadadiya:"કમલેશભાઈ અરવિંદભાઈ રાદડિયા",
        KashyapbhaiVinubhaiRadadiya:"કશ્યપભાઈ વિનુભાઈ રાદડિયા",
        KantibhaiLavjibhaiRadadiya:"કાંતિભાઇ લવજીભાઇ  રાદડિયા",
        KantibhaiGangdasbhaiRadadiya:"કાંતિભાઈ ગંગદાસભાઈ રાદડિયા",
        KantibhaiBhanabhaiRadadiya:"કાંતિભાઈ ભવાનભાઈ રાદડિયા",
        KantibhaiVitthalbhaiRadadiya:"કાંતિભાઈ વિઠ્ઠલભાઈ   રાદડિયા",
        KishorbhaiBabubhaiRadadiya:"કિશોરભાઈ બાબુભાઇ રાદડિયા",
        KetanbhaiRameshbhaiRadadiya:"કેતનભાઈ રમેશભાઈ રાદડિયા",
        KaushikDineshbhaiRadadiya:"કૌશિક દિનેશભાઇ રાદડિયા",
        GubharubhaiBhurabhaiRadadiya:"ગભરૂભાઇ ભુરાભાઇ રાદડિયા",
        GirdharbhaiPragjibhaiRadadiya:"ગીરધરભાઈ  પ્રાગજીભાઈ રાદડિયા",
        GordhanbhaiVeerjibhaiRadadiya:"ગોરધનભાઈ વીરજીભાઈ રાદડિયા",
        GautamhimatbhaiRadadiya:"ગૌતમભાઇ  હિંમતભાઇ રાદડિયા",
        ghanshyamnarayanbhaiRadadiya:"ઘનશ્યામ  નારણભાઇ રાદડિયા",
        GhanshyamikumarMansukhbhaiRadadiya:"ઘનશ્યામભાઈ  મનસુખભાઈ  રાદડિયા",
        GhanshyambhaiBalubhaiRadadiya:"ઘનશ્યામભાઈ બાલુભાઈ રાદડિયા",
        GhanshyambhaiVinubhaiRadadiya:"ઘનશ્યામભાઈ વિનુભાઈ રાદડિયા",
        GhanshyambhaiShambubhaiRadadiya:"ઘનશ્યામભાઈ શંભુભાઈ રાદડિયા",
        ChandubhaiDulabhaiRadadiya:"ચંદુભાઈ દુલાભાઇ રાદડિયા",
        ChimanbhaiVinubhaiRadadiya:"ચિમનભાઇ વિનુભાઈ રાદડિયા",
        ChimanbhaiDhirubhaiRadadiya:"ચિમનભાઇ ધીરુભાઈ રાદડિયા",
        ChunilalParshottamBhaiRadadiya:"ચુનિલાલ  પરશોતમભાઈ રાદડિયા",
        JagdishbhaiKantibhaiRadadiya:"જગદીશભાઈ કાંતિભાઈ રાદડિયા",
        JayrajArvindbhaiRadadiya:"જયરાજ અરવિંદભાઈ રાદડિયા",
        JaysukhbhaiKhimjibhaiRadadiya:"જયસુખભાઇ ખીમજીભાઈ રાદડિયા",
        JitubhaiKantibhaiRadadiya:"જીતુભાઇ કાંતિભાઈ રાદડિયા",
        TarachandbhaiVitthalbhaiRadadiya:"તારાચંદભાઇ વિઠ્ઠલભાઈ રાદડિયા",
        DalsukhbhaiRavjibhaiRadadiya:"દલસુખભાઈ રવજીભાઈ રાદડિયા",
        DineshbhaiParshtambhaiRadadiya:"દિનેશભાઇ પરષોત્તમભાઇ રાદડિયા",
        DulabhaiGopalbhaiRadadiya:"દુલાભાઇ ગોપાભાઇ રાદડિયા",
        DhirubhaiGopabhaiRadadiya:"ધીરુભાઈ ગોપાભાઇ રાદડિયા",
        DhirubhaiMuljibhaiRadadiya:"ધીરુભાઈ મુળજીભાઈ રાદડિયા",
        NarendrabhaiBavchandbhaiRadadiya:"નરેન્દ્રભાઈ બાવચંદભાઈ રાદડિયા",
        NathabhaiMadhubhaiRadadiya:"નાથાભાઈ મધુભાઈ રાદડિયા",
        narayanbhaiRanchodbhaiRadadiya:"નારણભાઇ રણછોડભાઇ રાદડિયા",
        NarayanbhaiDevrajbhaiRadadiya:"નારાયણભાઈ દેવરાજભાઇ રાદડિયા",
        NikunjbhaiHimatbhaiRadadiya:"નિકુંજભાઇ હિંમતભાઇ રાદડિયા",
        NikunjbhaiDhirubhaiRadadiya:"નિકુંજભાઈ ધીરુભાઈ રાદડિયા",
        NitinbhaiJaysukhbhaiRadadiya:"નિતીનભાઇ જયસુખભાઇ રાદડિયા",
        NipulbhaiMansukhbhaiRadadiya:"નિપુલભાઈ મનસુખભાઇ રાદડિયા",
        NileshbhaiBavchandbhaiRadadiya:"નિલેશભાઈ બાવચંદભાઈ રાદડિયા",
        NitinKumarJaysukhbhaiRadadiya:"નીતિનકુમાર જયસુખભાઇ રાદડિયા",
        PareshbhaipravinbhaiRadadiya:"પરેશભાઈ પ્રવીણભાઈ રાદડિયા",
        PrakashbhaiBabubhaiRadadiya:"પ્રકાશભાઈ બાબુભાઇ રાદડિયા",
        PravinbhaiRavjibhaiRadadiya:"પ્રવિણભાઇ રવજીભાઈ રાદડિયા",
        pravinbhaiGangdasbhaiRadadiya:"પ્રવીણભાઈ ગંગદાસભાઈ રાદડિયા",
        pravinbhaiRavjibhaiRadadiya:"પ્રવીણભાઈ રવજીભાઈ રાદડિયા",
        BabubhaiParatbhaiRadadiya:"બાબુભાઇ પોપટભાઈ રાદડિયા",
        BabubhaiBalubhaiRadadiya:"બાબુભાઇ બાલુભાઈ રાદડિયા",
        BalubhaiGopalbhaiRadadiya:"બાલુભાઈ ગોપાભાઇ રાદડિયા",
        BhanubhaiBhanabhaiRadadiya:"ભનુભાઈ ભવાનભાઈ રાદડિયા",
        BharatbhaiKhimjibhaiRadadiya:"ભરતભાઈ ખીમજીભાઈ રાદડિયા",
        BharatbhaiBabubhaiRadadiya:"ભરતભાઈ બાબુભાઇ રાદડિયા",
        BhaveshbhaiKhimjibhaiRadadiya:"ભાવેશભાઈ ખીમજીભાઈ રાદડિયા",
        BhikhubhaiLaljibhaiRadadiya:"ભીખુભાઇ લાલજીભાઈ રાદડિયા",
        ManthanArvindbhaiRadadiya:"મંથન  અરવિંદભાઈ રાદડિયા",
        MadhubhaiDevrajbhaiRadadiya:"મધુભાઈ દેવરાજભાઇ  રાદડિયા",
        MadhubhaiPragjibhaiRadadiya:"મધુભાઈ પ્રાગજીભાઈ રાદડિયા",
        ManjibhaiPremjibhaiRadadiya:"મનજીભાઇ પ્રેમજીભાઈ રાદડિયા",
        MansukhbhaiBhavanbhaiRadadiya:"મનસુખભાઇ ભવાનભાઇ રાદડિયા",
        MansukhbhaiRanchhodbhaiRadadiya:"મનસુખભાઇ રણછોડભાઈ રાદડિયા",
        MansukhbhaiVirjibhaiRadadiya:"મનસુખભાઇ વીરજીભાઈ રાદડિયા",
        MansukhbhaiBachubhaiRadadiya:"મનસુખભાઈ બચુભાઈ રાદડિયા",
        MayankbhaiGhanshyambhaiRadadiya:"મયંકભાઇ ઘનશ્યામભાઈ  રાદડિયા",
        MahirNileshbhaiRadadiya:"મહિર નિલેશભાઈ રાદડિયા",
        MaheshbhainarayanbhaiRadadiya:"મહેશભાઇ નારણભાઇ રાદડિયા",
        MaheshbhaiBhanubhaiRadadiya:"મહેશભાઈ ભનુભાઇ રાદડિયા",
        MukeshbhaiGirdharbhaiRadadiya:"મુકેશભાઈ ગીરધરભાઈ રાદડિયા",
        MukeshbhaiGordhanbhaiRadadiya:"મુકેશભાઈ ગોરધનભાઈ રાદડિયા",
        MaulikbhaiSureshbhaiRadadiya:"મૌલિકભાઈ સુરેશભાઈ  રાદડિયા",
        YogeshbhaiGordhanbhaiRadadiya:"યોગેશભાઈ ગોરધનભાઈ રાદડિયા",
        RajubhaiDulabhaiRadadiya:"રજુભાઈ દુલાભાઇ રાદડિયા",
        RameshbhaiLavjibhaiRadadiya:"રમેશભાઇ લવજીભાઇ  રાદડિયા",
        RameshbhaiParshtambhaiRadadiya:"રમેશભાઈ પરશોતમભાઈ રાદડિયા",
        RakshabhaiDevchandbhaiRadadiya:"રસિકભાઈ દેવચંદભાઈ રાદડિયા",
        RajeshbhaiLaljibhaiRadadiya:"રાજેશભાઈ  લાલજીભાઈ રાદડિયા",
        RajeshbhaiMadhubhaiRadadiya:"રાજેશભાઈ મધુભાઈ રાદડિયા",
        RamjibhaiGirharbhaiRadadiya:"રામજીભાઈ ગીરધરભાઈ રાદડિયા",
        LalitbhaiManjibhaiRadadiya:"લલિતભાઈ મનજીભાઇ રાદડિયા",
        LalitbhaiRameshbhaiRadadiya:"લલિતભાઈ રમેશભાઈ રાદડિયા",
        VajubhaiManjibhaiRadadiya:"વજુભાઇ મનજીભાઇ રાદડિયા",
        VajendrabhaiNathabhaiRadadiya:"વજેન્દ્રભાઈ  નાથાભાઈ રાદડિયા",
        VasudevbhaiGabhrubhaiRadadiya:"વાસુદેવભાઇ ગભરૂભાઇ રાદડિયા",
        VijaybhaiVitthalbhaiRadadiya:"વિજયભાઈ વિઠ્ઠલભાઈ રાદડિયા",
        VijaybhaiVinubhaiRadadiya:"વિજયભાઈ વિનુભાઈ રાદડિયા",
        VitthalbhaiGopabhaiRadadiya:"વિઠ્ઠલભાઈ ગોપાભાઈ રાદડિયા",
        VitthalbhaiMuljibhaiRadadiya:"વિઠ્ઠલભાઈ મુળજીભાઈ રાદડિયા",
        VinubhaiPopatbhaiRadadiya:"વિનુભાઈ પોપટભાઈ રાદડિયા",
        VinubhaiBalubhaiRadadiya:"વિનુભાઈ બાલુભાઈ રાદડિયા",
        VinubhaibhurabhaiRadadiya:"વિનુભાઈ ભુરાભાઇ રાદડિયા",
        VinubhaiVirjibhaiRadadiya:"વિનુભાઈ વીરજીભાઈ રાદડિયા",
        VimalbhaiBhanubhaiRadadiya:"વિમલભાઈ ભનુભાઇ રાદડિયા",
        VivekjivrajbhaiRadadiya:"વિવેક જીવરાજભાઈ રાદડિયા",
        VivekbhaiAshvinbhaiRadadiya:"વિવેકભાઈ અશ્વિનભાઈ રાદડિયા",
        VishalpravinbhaiRadadiya:"વિશાલ પ્રવીણભાઈ રાદડિયા",
        VishalkumarAshokbhaiRadadiya:"વિશાલકુમાર અશોકભાઈ રાદડિયા",
        SanjaybhaiMadhubhaiRadadiya:"સંજયભાઈ મધુભાઈ રાદડિયા",
        SanjaybhaiVitthalbhaiRadadiya:"સંજયભાઈ વિઠ્ઠલભાઈ રાદડિયા",
        SanjaybhaiVinubhaiRadadiya:"સંજયભાઈ વિનુભાઇ રાદડિયા",
        SatishbhaiVajibhaiRadadiya:"સતીશભાઈ વજીભાઈ રાદડિયા",
        SagarTarachandbhaiRadadiya:"સાગર તારાચંદભાઇ   રાદડિયા",
        SureshbhaiVitthalbhaiRadadiya:"સુરેશભાઈ વિઠ્ઠલભાઈ  રાદડિયા",
        SureshbhaiShambubhaiRadadiya:"સુરેશભાઈ શંભુભાઈ રાદડિયા",
        HariKrishanbhaiJaysukhbhaiRadadiya:"હરિકૃષ્ણભાઈ જયસુખભાઇ રાદડિયા",
        HarikrishnabhaiMukeshbhaiRadadiya:"હરિકૃષ્ણભાઈ મુકેશભાઈ રાદડિયા",
        HareshkumarJaysukhbhaiRadadiya:"હરેશકુમાર જયસુખભાઇ રાદડિયા",
        HareshbhaihimatbhaiRadadiya:"હરેશભાઈ હિમતભાઈ રાદડિયા",
        HarshadbhaiMansukhbhaiRadadiya:"હર્ષદભાઈ મનસુખભાઈ રાદડિયા",
        HarshilbhaiLalitbhaiRadadiya:"હર્ષીલભાઈ લલિતભાઈ રાદડિયા",
        HardikGhanshyambhaiRadadiya:"હાર્દિક ઘનશ્યામભાઈ રાદડિયા",
        HardikbhaiMansukhbhaiRadadiya:"હાર્દિકભાઈ મનસુખભાઇ  રાદડિયા",
        HardikbhaiMukeshbhaiRadadiya:"હાર્દિકભાઈ મુકેશભાઈ રાદડિયા",
        himatbhaigangdasbhaiRadadiya:"હિંમતભાઇ  ગંગદાસભાઇ  રાદડિયા",
        HimatbhaiLabhubhaiRadadiya:"હિંમતભાઇ લાભુભાઈ રાદડિયા",
        HimatbhaiGangdasbhaiRadadiya:"હિંમતભાઈ ગંગદાસભાઈ રાદડિયા",
        himatbhaijivrajbhaiRadadiya:"હિમતભાઈ જીવરાજભાઇ રાદડિયા",
        HirenPravinbhaiRadadiya:"હિરેન પ્રવિણભાઇ રાદડિયા",
        ParshtambhaiKeshavbhaiRadadiya:"પરષોત્તમભાઇ કેશવભાઈ રાદડિયા",
        VinubhaiParshottambhaiRadadiya:"વિનુભાઈ પરષોત્તમભાઇ રાદડિયા",
        MukeshbhaiParshitbhaiRadadiya:"મુકેશભાઈ પરષોત્તમભાઇ રાદડિયા",
        HarijibhaiJeevanbhaiRadadiya:"હરજીભાઇ જીવનભાઈ રાદડિયા",
        jaysukhbhaijivanbhaiRadadiya:"જયસુખભાઇ જીવનભાઈ રાદડિયા",
        BhupatbhaijivanbhaiRadadiya:"ભુપતભાઇ જીવનભાઈ રાદડિયા",
        krunalbhaiSureshbhaiDhankecha:"કૃણાલભાઈ સુરેશભાઈ ઢાંકેચા",
        GobarbhaiNarshibhaiDhankecha:"ગોબરભાઇ નરશીભાઈ ઢાંકેચા",
        GhanshyambhaibhupatbhaiDhankecha:"ઘનશ્યામભાઈ ભુપતભાઇ ઢાંકેચા",
        ParshotambhaiRavjibhaiDhankecha:"પરશોતમભાઈ રવજીભાઈ  ઢાંકેચા",
        PiyushbhaiRameshbhaiDhankecha:"પિયુષભાઇ રમેશભાઈ ઢાંકેચા",
        BalubhaiParshotambhaiDhankecha:"બલુભાઈ પરશોતમભાઈ ઢાંકેચા",
        BhargavbhaiDevchandbhaiDhankacha:"ભાર્ગવભાઇ દેવચંદભાઈ ઢાંકેચા",
        BhupatbhaiPopatbhaiDhankakecha:"ભુપતભાઇ પોપટભાઈ  ઢાંકેચા",
        MansukhbhaiDayalbhaiDhankecha:"મનસુખભાઇ દયાળભાઈ ઢાંકેચા",
        ManishbhaiDevchandbhaiDhankecha:"મનીષભાઈ દેવચંદભાઈ ઢાંકેચા",
        MayurbhaiGobarbhaiDhankecha:"મયુરભાઈ ગોબરભાઇ ઢાંકેચા",
        MehulbhaiRameshbhaiDhankacha:"મેહુલભાઈ રમેશભાઈ ઢાંકેચા",
        RameshbhaiRavjibhaiDhankecha:"રમેશભાઈ રાવજીભાઈ ઢાંકેચા",
        RajeshbhaiBhupatbhaiDhankecha:"રાજેશભાઈ ભુપતભાઇ ઢાંકેચા",
        SanjaybhaiBhupatbhaiDhankacha:"સંજયભાઈ ભુપતભાઇ ઢાંકેચા",
        SureshbhaiParshotambhaiDhankecha:"સુરેશભાઈ પરસોતમભાઇ ઢાંકેચા",
        JaysukhabhailabhubhaiShingala:"જયસુખભાઇ લાભુભાઈ શિંગાળા",
        KetanbhaiJaysukhabhaiShingala:"કેતનભાઈ જયસુખભાઇ શિંગાળા",
        GokulbhaiJaysukhabhaiShingala:"ગોકુલભાઈ જયસુખભાઇ શિંગાળા",
        AshokbhailabhubhaiShingala:"અશોકભાઈ લાભુભાઈ શિંગાળા",
        BhavinbhaiAshokbhaiShingala:"ભાવિનભાઈ અશોકભાઈ શિંગાળા",
        BhadreshbhaiAshokbhaiShingala:"ભદ્રેશભાઈ અશોકભાઈ શિંગાળા",
        NileshbhailabhubhaiShingala:"નિલેશભાઈ લાભુભાઈ શિંગાળા",
        GautambhaiNileshbhaiShingala:"ગૌતમભાઈ નિલેશભાઈ શિંગાળા",
        MaulikbhaiNileshbhaiShingala:"મૌલિકભાઈ નિલેશભાઈ શિંગાળા",
        GhanshyamlabhubhaiShingala:"ઘનશ્યામ લાભુભાઈ શિંગાળા",
        DevchandbhaiJethabhaiRadadiya:"દેવચંદભાઈ જેઠાભાઇ રાદડિયા",
        HarikrishnaBhaiDevchandbhaiRadadiya:"હરિકૃષ્ણભાઈ દેવચંદભાઈ રાદડિયા",
        HimmatbhaiRavjeebhaiSojitra:	"હિંમતભાઇ રવજીભાઈ સોજીત્રા",
        ChetanbhaiHimmatbhaiSojitra:	"ચેતનભાઈ હિંમતભાઇ સોજીત્રા",
        AshishbhaiHimmatbhaiSojitra:	"આશિષભાઇ હિંમતભાઇ સોજીત્રા",
        BabubhaiRavjeebhaiSojitra:	"બાબુભાઇ રવજીભાઈ સોજીત્રા",
        RameshbhaiRavjibhaiSojatra:	"રમેશભાઈ રવજીભાઈ સોજીત્રા",
        BharatbhaiDungarshbhaiRadadiya : "ભરતભાઈ ડુંગરશીભાઈ રાદડિયા",
        HarjibhaiDeungarshbhaiRadadiya : "હરજીભાઇ ડુંગરશીભાઈ રાદડિયા",
        HasuKantibhaiRadadiya : "હસુ કાંતિભાઈ રાદડિયા",
        IshwarbhaiKantibhaiRadadiya : "ઇશ્વરભાઈ કાંતિભાઈ રાદડિયા",
        KanubhaiRanchhodbhaiRadadiya : "કનુભાઈ રણછોડભાઈ રાદડિયા",
        KetanbabubhaiRadadiya : "કેતન બાબુભાઈ રાદડિયા",
        ManyakGhanshyambhaiRadadiya : "મંયક ઘનશ્યામભાઈ રાદડિયા",
        MehulbhaiGobarbhaiRadadiya : "મેહુલભાઈ ગોબરભાઈ રાદડિયા",
        NikulbhaiDhirubhaiRadadiya : "નિકુલભાઈ ધીરુભાઈ રાદડિયા",
        SudhirbhaiBharatbhaiRadadiya : "સુધીરભાઇ ભરતભાઇ રાદડિયા",
        Uttamkanubhairadadiya: "ઉત્તમ કનુભાઈ રાદડિયા",
        ViralRamesbhaiRadadiya : "વિરલ રમેશભાઈ રાદડિયા",
        YogeshbhaiHarjibhaiRadadiya : "યોગેશભાઈ હરજીભાઈ રાદડિયા",
        GobarbhaiNagjibhaiRadadiya:	"ગોબરભાઇ નાગજીભાઈ રાદડિયા",
        DipakbhaigobarbhaiRadadiya	:"દીપકભાઈ ગોબરભાઇ રાદડિયા",
        ManthanbabubhaiRadadiya:"મંથન બાબુભાઇ રાદડિયા"
    },

});
export default strings;